theme = "emily"
baseURL = "https://boring-curie-4938fd.netlify.com/"
# baseURL = "https://christine.dimitra-esthetica.be/"
languageCode = "nl-BE"
title = "Medische pedicure Christine en Esthetica Dimitra"
# relativeURLS = true
# canonifyurls = true
# enableEmoji = true

[menu]
	[[menu.main]]
		name = "Home"
		url = "/"
		identifier = "home"
		weight = 10

	[[menu.main]]
		name = "Prijzen"
		url = "/prijzen/"
		identifier = "prijzen"
		weight = 20

	[[menu.main]]
		name = "Over mij"
		url = "/over-mij/"
		identifier = "over-mij"
		weight = 30
